// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ToastController from "./toast_controller"
import SearchController from "./search_controller"
import ClipboardController from "./clipboard_controller"

application.register("toast", ToastController)
application.register("search", SearchController)
application.register("clipboard", ClipboardController)

